[test]
levels = ["syntax", "install", "registration", "instantiation", "execution"]

[test.workflows]
cpu = ["!pano"]
gpu = "all"

[test.platforms]
linux = true
macos = true
windows = true
windows_portable = true
